name: ludo_global
description: Ludo Global - Normal and Power Ludo built with Flutter.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  audioplayers: ^6.5.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/game/pawns/
    - assets/game/dice/
    - assets/game/powers/
    - assets/game/board/
    - assets/audio/game/
